services:
  db:
    container_name: ${APP_NAME}-db
    image: mariadb:latest
    env_file:
      - path: .env
        required: false
      - path: .env.example
        required: true
    ports:
      - "${MARIADB_PORT:-3306}:${MARIADB_PORT:-3306}"
    volumes:
      - mysql:/var/lib/mysql/
    command:
      - mariadbd
      - --port=${MARIADB_PORT:-3306}

  redis:
    container_name: ${APP_NAME}-redis
    image: redis:latest
    env_file:
      - path: .env
        required: false
      - path: .env.example
        required: true

  php:
    container_name: ${APP_NAME}-php
    extends:
      file: .docker/local/php-docker-compose.yaml
      service: base-php
    command:
      - php-fpm

  horizon:
    container_name: ${APP_NAME}-horizon
    depends_on:
      - redis
      - db
    extends:
      file: .docker/local/php-docker-compose.yaml
      service: base-php
    command:
      - php
      - artisan
      - horizon

  schedule:
    container_name: ${APP_NAME}-schedule
    extends:
      file: .docker/local/php-docker-compose.yaml
      service: base-php
    command:
      - php
      - artisan
      - schedule:work

  websockets:
    container_name: ${APP_NAME}-websockets
    image: dannypas00/laravel-fpm:8.2
    extends:
      file: .docker/local/php-docker-compose.yaml
      service: base-php
    command:
      - php
      - artisan
      - reverb:start
      - --port=6001
      - --host=0.0.0.0
    ports:
      - "6001:6001"

  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:latest
    env_file:
      - path: .env
        required: false
      - path: .env.example
        required: true
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - .docker/local/nginx-includes:/etc/nginx/conf.d
      - ./:/var/www/project

  mailpit:
    container_name: ${APP_NAME}-mailpit
    image: axllent/mailpit:latest
    env_file:
      - path: .env
        required: false
      - path: .env.example
        required: true
    ports:
      - "${MAILPIT_PORT:-1025}:1025"
      - "${MAILPIT_INTERFACE_PORT:-8025}:8025"

volumes:
    mysql:
