services:
  db:
    container_name: ${APP_NAME}-db
    image: mariadb:latest
    env_file:
      - path: .env
        required: true
    ports:
      - "${MARIADB_PORT:-3306}:${MARIADB_PORT:-3306}"
    volumes:
      - mysql:/var/lib/mysql/
    command:
      - mariadbd
      - --port=${MARIADB_PORT:-3306}

  redis:
    container_name: ${APP_NAME}-redis
    image: redis:latest
    env_file:
      - path: .env
        required: true

  php:
    container_name: ${APP_NAME}-php
    extends:
      file: .docker/local/php-docker-compose.yaml
      service: base-php
    command:
      - sleep
      - infinity

  node:
    container_name: ${APP_NAME}-node
    image: node:22
    ports:
      - 5174:5174
    user: ${CUSTOM_USER:-1000}
    working_dir: /app
    command:
      - npx
      - dev
      - --
      - --host
      - --port=5174
    volumes:
      - ./:/app
      - ${NPM_CACHE_DIR:-$HOME/.npm}:/var/www/.npm:rw
    profiles:
      - dev

  horizon:
    container_name: ${APP_NAME}-horizon
    depends_on:
      - redis
      - db
    extends:
      file: .docker/local/php-docker-compose.yaml
      service: base-php
    command:
      - php
      - artisan
      - horizon

  schedule:
    container_name: ${APP_NAME}-schedule
    extends:
      file: .docker/local/php-docker-compose.yaml
      service: base-php
    command:
      - php
      - artisan
      - schedule:work

  reverb:
    container_name: ${APP_NAME}-reverb
    extends:
      file: .docker/local/php-docker-compose.yaml
      service: base-php
    command:
      - php
      - artisan
      - reverb:start
      - --port=6001
      - --host=0.0.0.0
      - --debug
    ports:
      - "${REVERB_PORT:-6001}:6001"

  frank:
    container_name: ${APP_NAME}-frank
    build:
      dockerfile: .docker/local/frankenphp.Dockerfile
      context: .
      args:
        USER: ${CUSTOM_USER:-app}
    env_file:
      - path: .env
        required: true
    depends_on:
      - reverb
    ports:
      - "${FRANKENPHP_PORT:-80}:8000"
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    tty: true
    entrypoint: ["php", "artisan", "octane:frankenphp", "--watch", "--caddyfile=/app/.docker/local/Caddyfile"]

  mailpit:
    container_name: ${APP_NAME}-mailpit
    image: axllent/mailpit:latest
    env_file:
      - path: .env
        required: true
    ports:
      - "${MAILPIT_PORT:-1025}:1025"
      - "${MAILPIT_INTERFACE_PORT:-8025}:8025"

volumes:
    mysql:
    npm-cache:
    caddy_data:
    caddy_config:
