services:
  x-function-base: &base
    env_file:
      - path: .env
        required: true
    profiles:
      - dev
      - prod
    user: ${CUSTOM_USER:-1000}

  db:
    <<: *base
    container_name: ${APP_NAME}-db
    image: mariadb:latest
    user: root
    ports:
      - "${MARIADB_PORT:-3306}:${MARIADB_PORT:-3306}"
    volumes:
      - laravel-template-project-mysql:/var/lib/mysql/
    command:
      - mariadbd
      - --port=${MARIADB_PORT:-3306}

  redis:
    <<: *base
    container_name: ${APP_NAME}-redis
    image: redis:latest

  php:
    <<: *base
    container_name: ${APP_NAME}-php
    extends:
      file: .docker/local/php-docker-compose.yaml
      service: base-php
    command:
      - sleep
      - infinity
    profiles: !override
      - dev

  node:
    <<: *base
    container_name: ${APP_NAME}-node
    image: dannypas00/node
    ports:
      - 5174:5174
    working_dir: /app
    command:
      - npx
      - vite
      - --host
      - --port=5174
    volumes:
      - ./:/app
      - ${NPM_CACHE_DIR:-$HOME/.npm}:/var/www/.npm:rw
    profiles: !override
      - dev

  horizon:
    <<: *base
    container_name: ${APP_NAME}-horizon
    depends_on:
      - redis
      - db
    extends:
      file: .docker/local/php-docker-compose.yaml
      service: base-php
    command:
      - php
      - artisan
      - horizon

  schedule:
    <<: *base
    container_name: ${APP_NAME}-schedule
    extends:
      file: .docker/local/php-docker-compose.yaml
      service: base-php
    command:
      - php
      - artisan
      - schedule:work

  reverb:
    <<: *base
    container_name: ${APP_NAME}-reverb
    extends:
      file: .docker/local/php-docker-compose.yaml
      service: base-php
    command:
      - php
      - artisan
      - reverb:start
      - --port=6001
      - --host=0.0.0.0
      - --debug
    ports:
      - "${REVERB_PORT:-6001}:6001"

  frank:
    <<: *base
    container_name: ${APP_NAME}-frank
    build:
      dockerfile: .docker/local/frankenphp.Dockerfile
      context: .
      args:
        USER: ${CUSTOM_USER:-app}
    depends_on:
      - reverb
    ports:
      - "${FRANKENPHP_PORT:-80}:8000"
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    tty: true
    command: [ "php", "artisan", "octane:frankenphp", "--watch", "--caddyfile=/app/.docker/local/Caddyfile" ]

  mailpit:
    <<: *base
    container_name: ${APP_NAME}-mailpit
    image: axllent/mailpit:latest
    ports:
      - "${MAILPIT_PORT:-1025}:1025"
      - "${MAILPIT_INTERFACE_PORT:-8025}:8025"

volumes:
  laravel-template-project-mysql:
  npm-cache:
  caddy_data:
  caddy_config:
