services:
  x-function-base: &base
    restart: unless-stopped
    image: alpine
    env_file:
      - path: .env
        required: true
    profiles:
      - dev
      - prod
    user: ${CUSTOM_USER:-1000}

  x-function-php: &php
    restart: unless-stopped
    user: ${CUSTOM_USER:-1000}
    build:
      dockerfile: cli.Dockerfile
      context: .docker/local/
    environment:
      APP_NAME: "laravel-template-project"
    working_dir: /app
    env_file:
      - path: .env
        required: true
    command:
      - php
      - artisan
      - list
    profiles:
      - dev
      - prod
    volumes:
      - ./:/app:rw
      - ./.docker/local/tests/output:/opt/phpstorm-coverage:rw
      - $HOME/.config:/home/app/.config:rw
      - ${NPM_CACHE_DIR:-npm-cache}:/home/app/.npm:rw
      - ${COMPOSER_CACHE:-composer-cache}:/home/app/.cache:rw

  db:
    <<: *base
    container_name: ${APP_NAME}-db
    image: mariadb:latest
    user: root
    ports:
      - "${MARIADB_PORT:-3306}:${MARIADB_PORT:-3306}"
    volumes:
      - laravel-template-project-mysql:/var/lib/mysql/
    command:
      - mariadbd
      - --port=${MARIADB_PORT:-3306}

  redis:
    <<: *base
    container_name: ${APP_NAME}-redis
    image: redis:latest
    command:
      - redis-server
      - --save
      - ""
      - --appendonly
      - no

  php:
    <<: *php
    container_name: ${APP_NAME}-php
    command:
      - sleep
      - infinity
    profiles: !override
      - dev

  node:
    <<: *base
    container_name: ${APP_NAME}-node
    image: dannypas00/node
    user: ${CUSTOM_USER:-1000}
    ports:
      - 5174:5174
    working_dir: /app
    command:
      - npx
      - vite
      - --host
      - --port=5174
    volumes:
      - ./:/app:rw
      - ${NPM_CACHE_DIR:-npm-cache}:/home/node/.npm:rw
    profiles: !override
      - dev

  horizon:
    <<: *php
    container_name: ${APP_NAME}-horizon
    depends_on:
      - redis
      - db
    command:
      - php
      - artisan
      - horizon
    profiles:
      - dev
      - prod

  schedule:
    <<: *php
    container_name: ${APP_NAME}-schedule
    command:
      - php
      - artisan
      - schedule:work
    profiles:
      - dev
      - prod

  reverb:
    <<: *php
    container_name: ${APP_NAME}-reverb
    command:
      - php
      - artisan
      - reverb:start
      - --port=6001
      - --host=0.0.0.0
      - --debug
    ports:
      - "${REVERB_PORT:-6001}:6001"

  frank:
    <<: *php
    container_name: ${APP_NAME}-frank
    build:
      dockerfile: .docker/local/frankenphp.Dockerfile
      context: .
      args:
        USER: ${CUSTOM_USER:-app}
    depends_on:
      - reverb
    ports:
      - "${FRANKENPHP_PORT:-80}:8000"
    volumes:
      - ./:/app:rw
      - ./.docker/local/tests/output:/opt/phpstorm-coverage:rw
      - $HOME/.config:/home/app/.config:rw
      - ${NPM_CACHE_DIR:-$HOME/.npm}:/home/app/.npm:rw
      - ${COMPOSER_CACHE:-composer-cache}:/home/app/.cache:rw
      - caddy_data:/data
      - caddy_config:/config
    tty: true
    command:
      - php
      - artisan
      - octane:frankenphp
      - --watch
      - --caddyfile=/app/.docker/local/Caddyfile

  mailpit:
    <<: *base
    container_name: ${APP_NAME}-mailpit
    image: axllent/mailpit:latest
    ports:
      - "${MAILPIT_PORT:-1025}:1025"
      - "${MAILPIT_INTERFACE_PORT:-8025}:8025"

volumes:
  laravel-template-project-mysql:
  npm-cache:
  composer-cache:
  caddy_data:
  caddy_config:
