services:
  base-php:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ../../.env
    user: 1000:1000
    working_dir: /var/www/project
    depends_on:
      - db
      - redis
    command:
      - php
      - artisan
      - list
    volumes:
      - ../../:/var/www/project
      - ./tests/output:/opt/phpstorm-coverage
