name: "Test integration on push"
on:
  push:
    branches:
      - master
      - develop
      - install

jobs:
  Run-make-with-integration-tests:
    - uses: actions/checkout@v4
      name: Checkout
    - uses: docker/setup-buildx-action@v3.4.0
      name: Setup buildx
    - run: make
      name: Run Make
