name: "Test integration on push"
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop
      - master

jobs:
  Run-make-with-integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout

    - uses: docker/setup-buildx-action@v3.4.0
      name: Setup buildx

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - run: cp .env.example .env

    - run: echo CUSTOM_USER=${UID} >> .env

    - run: make NODE_LOCAL=true -B
      name: Run Make
