name: "Test on push"
on:
  push:
  pull_request:

jobs:
  Run-composer-test:
    runs-on: ubuntu-latest
    container: "dannypas00/php-cli"
    steps:
      - name: Run composer test
        run: composer test
