name: "Test integration on push"
on:
  push:
    branches:
      - master
      - develop
      - install

jobs:
  Run-make-with-integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout

    - uses: actions/cache@v3
      with:
        path: composer_cache.tar.gz
        key: composer-cache

    - run: tar -xzf composer_cache.tar.gz composer-cache || mkdir composer-cache

    - uses: docker/setup-buildx-action@v3.4.0
      name: Setup buildx

    - run: make NPM=npm -B package.json

    - uses: actions/setup-node@v4
      with:
        cache: 'npm'

    - run: CUSTOM_USER=1001 COMPOSER_CACHE=`pwd`/composer-cache make NPM=npm -B
      name: Run Make

    - run: tar -czf composer_cache.tar.gz composer-cache
