name: "Test integration on push"
on:
  push:
    branches:
      - master
      - develop
      - install

jobs:
  Run-make-with-integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout
    - uses: docker/setup-buildx-action@v3.4.0
      name: Setup buildx
    - run: pwd && ls -lah && echo $UID && echo $GID
    - run: docker compose run php ls -lah
    - run: make -B
      name: Run Make
