name: "Test integration on push"
on:
  push:
    branches:
      - master
      - develop
      - install

jobs:
  Run-make-with-integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout
    - uses: docker/setup-buildx-action@v3.4.0
      name: Setup buildx
    - run: mkdir /tmp/.npm
    - run: CUSTOM_USER=1001 NPM_CACHE_DESTINATION=/.npm make ENV=production -B
      name: Run Make
