name: "Test integration on push"
on:
  push:
    branches:
      - master
      - develop
      - install
jobs:
  Run-make-with-integration-tests:
    container:
      image: dannypas00/laravel-fpm:8.2
      options: --user 1000:1000
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout

    - uses: actions/cache@v3
      name: Restore compose cache
      with:
        path: composer-cache
        key: composer-cache

    - uses: docker/setup-buildx-action@v3.4.0
      name: Setup buildx

    - run: make NPM=npm -B package.json
      name: Create package-lock

    - uses: actions/setup-node@v4
      name: NPM cache
      with:
        cache: 'npm'

    - run: make COMPOSER=composer NPM=npm -B
      name: Run Make
