name: "Test integration on push"
on:
  push:
    branches:
      - master
      - develop
      - install

jobs:
  - uses: actions/checkout@v4

  - uses: docker/setup-buildx-action@v3.4.0

  - run: make
