name: "Test on push"
on:
  push:
  pull_request:

jobs:
  Run-composer-test:
    runs-on: ubuntu-latest
    container:
      image: "dannypas00/php-cli"
      options: --user root
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Install
        run: composer install

      - name: Run composer test
        run: composer run test
